### ISSUE TITLE
Feature suggestion - version tag support?

### ISSUE THREAD

**Issue by mix3d** [cnring18/cordova-build-increment#1]
Is there a possibility to let this run on just the `version` tag, so we don't HAVE to separate the ios and Android builds, or as a fallback if the platform specific versions are not present?

I may end up just copying the main bits to make a separately runnable function to update both in unison, since we will be releasing numerically matched versions on their own, but wanted to ask.

**Comment by cnring18** [comment]
Yes I can change it to work on the version tag. I am thinking of using a flag similar to the isRelease flag for only building on releases. This one will determine if the version tag or the platform specific tags should be used.

**Comment by mix3d** [comment]
@cnring18, sounds like a plan!
