### ISSUE TITLE
Change script defaults / increment method

### ISSUE THREAD

**Issue by mix3d** [cnring18/cordova-build-increment#2]
Last suggestion, that I had while attempting to deploy this, is the need to change the script text itself to switch between increment release-only vs all builds. Ideally, this would be handled with additional argv's, otherwise this plugin is unable to be deployed ready-to-go with npm install; this adds extra work whenever setting up build environments on new machines.

**Comment by cnring18** [comment]
What if the option to change the script text remains, but the option to increment using arguments is added?
