### ISSUE TITLE
Enable ability to specify version number as parameter

### ISSUE THREAD

**Issue by bc3tech** [cnring18/cordova-build-increment#4]
It's not clear to me that this tool can be used to _set_ the version number at build time.

Most CI systems keep track of a build identifier and it can be used during the build. I would like to be able to do something like `cordova build --version x.y.<build id>` using this module.

If this is possible, do let me know how. All I see from `Readme.md` is the ability to either increment or not increment; not the ability to stamp a specific version on the output.

Thanks!

**Comment by cnring18** [comment]
@bc3tech the way this hook works, I don't think its possible to achieve what you are asking. The current version/build numbers are not provided in the context that the hook is executed with. And at the point of execution, cordova has already read config.xml so writing to it won't affect the current build execution.

**Comment by bc3tech** [comment]
ok. I have found other `gulp` tasks to do this functionality. thanks for the reply.
